# install requirements, setup environment, etc.
FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.cli.sh .
RUN chmod +x entrypoint.cli.sh

# Copy application code
COPY . .

# Set the entry point for the container
ENTRYPOINT ["./cli/entrypoint.cli.sh"]