# install requirements, setup environment, etc.
FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./docker/entrypoint.cli.sh /usr/local/bin/entrypoint.cli.sh
RUN chmod +x /usr/local/bin/entrypoint.cli.sh

# Copy application code
COPY . .

# Set the entry point for the container
ENTRYPOINT ["entrypoint.cli.sh"]