# install requirements, setup environment, etc.
FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.web.sh .
RUN chmod +x entrypoint.web.sh

# Copy application code
COPY . .

EXPOSE 8501

# Set the entry point for the container
ENTRYPOINT ["./entrypoint.web.sh"]